name: 'Approve Functional Tests'
on:
  pull_request:
    branches:
      - main
      - features/*
      - release/*
# Ignore updating of versions.yaml file to avoid unnecessary functional tests
    paths-ignore:
      - 'versions.yaml'
        
jobs:
  approve-functional-tests-run:
    name: 'Approve Functional Tests'
    runs-on: ubuntu-latest
    environment: functional-tests
    steps:
    - name: Use custom actions
      uses: actions/checkout@v3
    - name: Save PR number
      uses: ./.github/actions/save-pr-as-artifact
