name: 'Approve Functional Tests'
on:
  pull_request:
    branches:
      - main
      - features/*
      - release/*
    # Ignore exclusive changes to the versions.yaml file - are handled via skip-functional-tests.yaml
    paths-ignore: 
      - 'versions.yaml'  
jobs:
  approve-functional-tests-run:
    name: 'Approve Functional Tests'
    runs-on: ubuntu-latest
    environment: functional-tests
    steps:
    - name: Use custom actions
      uses: actions/checkout@v4
    - name: Save PR number
      uses: ./.github/actions/save-pr-as-artifact